// swift-tools-version: 5.9
import PackageDescription

// Generated by the Pipl iOS SDK release pipeline. Do not edit by hand.
let package = Package(
    name: "PiplDeviceIntelligence",
    platforms: [
        .iOS(.v16)
    ],
    products: [
        .library(
            name: "PiplDeviceIntelligence",
            targets: ["PiplDeviceIntelligence"]
        )
    ],
    targets: [
        .binaryTarget(
            name: "PiplDeviceIntelligence",
            url: "https://static.pipl.com/sdk/device-intelligence-ios/1.2.3/PiplDeviceIntelligence.xcframework.zip",
            checksum: "acd07f5559edf0b3ec37582282e47741ab1c7cb71dbcaef85d2bf0cdaf3fcae6"
        )
    ]
)
