// swift-tools-version: 5.9
import PackageDescription

// Generated by the Pipl iOS SDK release pipeline. Do not edit by hand.
let package = Package(
    name: "PiplDeviceIntelligence",
    platforms: [
        .iOS(.v16)
    ],
    products: [
        .library(
            name: "PiplDeviceIntelligence",
            targets: ["PiplDeviceIntelligence"]
        )
    ],
    targets: [
        .binaryTarget(
            name: "PiplDeviceIntelligence",
            url: "https://static.pipl.com/sdk/device-intelligence-ios/1.2.1-rc.1/PiplDeviceIntelligence.xcframework.zip",
            checksum: "0203d522032d137420d550256d51e77f3ee28aa1bf4d24abd96f280d0c3d43ac"
        )
    ]
)
