// swift-tools-version: 5.9
import PackageDescription

// Generated by the Pipl iOS SDK release pipeline. Do not edit by hand.
let package = Package(
    name: "PiplDeviceIntelligence",
    platforms: [
        .iOS(.v16)
    ],
    products: [
        .library(
            name: "PiplDeviceIntelligence",
            targets: ["PiplDeviceIntelligence"]
        )
    ],
    targets: [
        .binaryTarget(
            name: "PiplDeviceIntelligence",
            url: "https://static.pipl.com/sdk/device-intelligence-ios/1.2.2/PiplDeviceIntelligence.xcframework.zip",
            checksum: "0db89327d9f900d71e9a339807a033207c310d2d1ae127e563b8fa5754f376da"
        )
    ]
)
