# Generated by the Pipl iOS SDK release pipeline. Do not edit by hand.
Pod::Spec.new do |s|
  s.name             = 'PiplDeviceIntelligence'
  s.version          = '1.2.0-rc.2'
  s.summary          = 'Pipl Device Intelligence SDK for iOS — device fingerprinting and trust-signal collection.'
  s.description      = <<-DESC
    Native iOS SDK for collecting device fingerprinting attributes and posting them
    encrypted to the Pipl Device Intelligence service. Distributed as a binary XCFramework.
  DESC

  s.homepage         = 'https://github.com/piplcom/device-intelligence-sdk-ios-dist'
  s.license          = { :type => 'Proprietary' }
  s.author           = { 'Pipl' => 'engineering@pipl.com' }

  s.ios.deployment_target = '16.0'
  s.swift_versions   = ['6.0']

  s.source           = { :http => 'https://storage.googleapis.com/pipl-static-content/sdk/device-intelligence-ios/1.2.0-rc.2/PiplDeviceIntelligence.xcframework.zip' }
  s.vendored_frameworks = 'PiplDeviceIntelligence.xcframework'
end
